<?php

namespace Bellwether\BWCMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRelationRepository extends EntityRepository
{
}
