<?php

namespace Bellwether\BWCMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThumbStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaleRepository extends EntityRepository
{
}
